[2023-10-03 13:51:12,932] {processor.py:153} INFO - Started process (PID=1180) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:51:12,933] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:51:12,934] {logging_mixin.py:115} INFO - [2023-10-03 13:51:12,934] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:51:12,962] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:51:13,351] {logging_mixin.py:115} INFO - [2023-10-03 13:51:13,351] {manager.py:508} INFO - Created Permission View: can read on DAG:dag_con_catchup
[2023-10-03 13:51:13,434] {logging_mixin.py:115} INFO - [2023-10-03 13:51:13,434] {manager.py:508} INFO - Created Permission View: can delete on DAG:dag_con_catchup
[2023-10-03 13:51:13,517] {logging_mixin.py:115} INFO - [2023-10-03 13:51:13,517] {manager.py:508} INFO - Created Permission View: can edit on DAG:dag_con_catchup
[2023-10-03 13:51:13,518] {logging_mixin.py:115} INFO - [2023-10-03 13:51:13,518] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:51:13,534] {logging_mixin.py:115} INFO - [2023-10-03 13:51:13,534] {dag.py:2439} INFO - Creating ORM DAG for dag_con_catchup
[2023-10-03 13:51:13,558] {logging_mixin.py:115} INFO - [2023-10-03 13:51:13,558] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:51:13,666] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.738 seconds
[2023-10-03 13:51:44,067] {processor.py:153} INFO - Started process (PID=1233) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:51:44,068] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:51:44,069] {logging_mixin.py:115} INFO - [2023-10-03 13:51:44,068] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:51:44,088] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:51:44,118] {logging_mixin.py:115} INFO - [2023-10-03 13:51:44,118] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:51:44,257] {logging_mixin.py:115} INFO - [2023-10-03 13:51:44,257] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:51:44,819] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.757 seconds
[2023-10-03 13:52:14,906] {processor.py:153} INFO - Started process (PID=1295) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:52:14,908] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:52:14,910] {logging_mixin.py:115} INFO - [2023-10-03 13:52:14,910] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:52:14,954] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:52:14,985] {logging_mixin.py:115} INFO - [2023-10-03 13:52:14,985] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:52:15,122] {logging_mixin.py:115} INFO - [2023-10-03 13:52:15,122] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:52:15,176] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.279 seconds
[2023-10-03 13:52:45,241] {processor.py:153} INFO - Started process (PID=1348) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:52:45,242] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:52:45,243] {logging_mixin.py:115} INFO - [2023-10-03 13:52:45,243] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:52:45,262] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:52:45,299] {logging_mixin.py:115} INFO - [2023-10-03 13:52:45,299] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:52:45,456] {logging_mixin.py:115} INFO - [2023-10-03 13:52:45,456] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:52:45,500] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.262 seconds
[2023-10-03 13:53:15,778] {processor.py:153} INFO - Started process (PID=1416) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:53:15,779] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:53:15,780] {logging_mixin.py:115} INFO - [2023-10-03 13:53:15,780] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:53:15,797] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:53:15,852] {logging_mixin.py:115} INFO - [2023-10-03 13:53:15,852] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:53:15,981] {logging_mixin.py:115} INFO - [2023-10-03 13:53:15,981] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:53:16,053] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.280 seconds
[2023-10-03 13:53:46,565] {processor.py:153} INFO - Started process (PID=1470) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:53:46,566] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:53:46,567] {logging_mixin.py:115} INFO - [2023-10-03 13:53:46,567] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:53:46,588] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:53:46,616] {logging_mixin.py:115} INFO - [2023-10-03 13:53:46,616] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:53:46,742] {logging_mixin.py:115} INFO - [2023-10-03 13:53:46,742] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:53:46,780] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.221 seconds
[2023-10-03 13:54:17,000] {processor.py:153} INFO - Started process (PID=1532) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:54:17,002] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:54:17,003] {logging_mixin.py:115} INFO - [2023-10-03 13:54:17,003] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:54:17,042] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:54:17,075] {logging_mixin.py:115} INFO - [2023-10-03 13:54:17,075] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:54:17,212] {logging_mixin.py:115} INFO - [2023-10-03 13:54:17,212] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:54:17,246] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.252 seconds
[2023-10-03 13:54:48,038] {processor.py:153} INFO - Started process (PID=1594) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:54:48,039] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:54:48,040] {logging_mixin.py:115} INFO - [2023-10-03 13:54:48,040] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:54:48,069] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:54:48,097] {logging_mixin.py:115} INFO - [2023-10-03 13:54:48,097] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:54:48,226] {logging_mixin.py:115} INFO - [2023-10-03 13:54:48,226] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:54:48,261] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.230 seconds
[2023-10-03 13:55:18,329] {processor.py:153} INFO - Started process (PID=1647) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:55:18,331] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:55:18,331] {logging_mixin.py:115} INFO - [2023-10-03 13:55:18,331] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:55:18,349] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:55:18,376] {logging_mixin.py:115} INFO - [2023-10-03 13:55:18,376] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:55:18,502] {logging_mixin.py:115} INFO - [2023-10-03 13:55:18,501] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:55:18,536] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.209 seconds
[2023-10-03 13:55:48,776] {processor.py:153} INFO - Started process (PID=1709) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:55:48,777] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:55:48,778] {logging_mixin.py:115} INFO - [2023-10-03 13:55:48,778] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:55:48,799] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:55:48,827] {logging_mixin.py:115} INFO - [2023-10-03 13:55:48,826] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:55:48,966] {logging_mixin.py:115} INFO - [2023-10-03 13:55:48,966] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:55:49,000] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.227 seconds
[2023-10-03 13:56:19,401] {processor.py:153} INFO - Started process (PID=1763) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:56:19,401] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:56:19,402] {logging_mixin.py:115} INFO - [2023-10-03 13:56:19,402] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:56:19,418] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:56:19,579] {logging_mixin.py:115} INFO - [2023-10-03 13:56:19,579] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:56:19,604] {logging_mixin.py:115} INFO - [2023-10-03 13:56:19,604] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:56:19,636] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.239 seconds
[2023-10-03 13:56:49,863] {processor.py:153} INFO - Started process (PID=1825) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:56:49,864] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:56:49,865] {logging_mixin.py:115} INFO - [2023-10-03 13:56:49,865] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:56:49,892] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:56:50,023] {logging_mixin.py:115} INFO - [2023-10-03 13:56:50,023] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:56:50,043] {logging_mixin.py:115} INFO - [2023-10-03 13:56:50,043] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:56:50,110] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.253 seconds
[2023-10-03 13:57:20,184] {processor.py:153} INFO - Started process (PID=1878) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:57:20,186] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:57:20,187] {logging_mixin.py:115} INFO - [2023-10-03 13:57:20,187] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:57:20,208] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:57:20,355] {logging_mixin.py:115} INFO - [2023-10-03 13:57:20,355] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:57:20,377] {logging_mixin.py:115} INFO - [2023-10-03 13:57:20,377] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:57:20,406] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.225 seconds
[2023-10-03 13:57:51,259] {processor.py:153} INFO - Started process (PID=1940) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:57:51,261] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:57:51,262] {logging_mixin.py:115} INFO - [2023-10-03 13:57:51,262] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:57:51,279] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:57:51,410] {logging_mixin.py:115} INFO - [2023-10-03 13:57:51,410] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:57:51,429] {logging_mixin.py:115} INFO - [2023-10-03 13:57:51,429] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:57:51,466] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.212 seconds
[2023-10-03 13:58:21,593] {processor.py:153} INFO - Started process (PID=2002) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:58:21,594] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:58:21,594] {logging_mixin.py:115} INFO - [2023-10-03 13:58:21,594] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:58:21,609] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:58:21,747] {logging_mixin.py:115} INFO - [2023-10-03 13:58:21,747] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:58:21,768] {logging_mixin.py:115} INFO - [2023-10-03 13:58:21,768] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:58:21,810] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.220 seconds
[2023-10-03 13:58:52,041] {processor.py:153} INFO - Started process (PID=2055) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:58:52,043] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:58:52,044] {logging_mixin.py:115} INFO - [2023-10-03 13:58:52,044] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:58:52,068] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:58:52,202] {logging_mixin.py:115} INFO - [2023-10-03 13:58:52,202] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:58:52,226] {logging_mixin.py:115} INFO - [2023-10-03 13:58:52,226] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:58:52,255] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.220 seconds
[2023-10-03 13:59:22,748] {processor.py:153} INFO - Started process (PID=2118) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:59:22,749] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:59:22,750] {logging_mixin.py:115} INFO - [2023-10-03 13:59:22,749] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:59:22,770] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:59:22,901] {logging_mixin.py:115} INFO - [2023-10-03 13:59:22,901] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:59:22,920] {logging_mixin.py:115} INFO - [2023-10-03 13:59:22,920] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:59:22,957] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.213 seconds
[2023-10-03 13:59:53,704] {processor.py:153} INFO - Started process (PID=2171) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:59:53,705] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 13:59:53,707] {logging_mixin.py:115} INFO - [2023-10-03 13:59:53,706] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:59:53,725] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 13:59:53,884] {logging_mixin.py:115} INFO - [2023-10-03 13:59:53,884] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 13:59:53,912] {logging_mixin.py:115} INFO - [2023-10-03 13:59:53,912] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 13:59:53,940] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.239 seconds
[2023-10-03 14:00:24,713] {processor.py:153} INFO - Started process (PID=2233) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:00:24,714] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:00:24,716] {logging_mixin.py:115} INFO - [2023-10-03 14:00:24,715] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:00:24,740] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:00:24,863] {logging_mixin.py:115} INFO - [2023-10-03 14:00:24,863] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:00:24,883] {logging_mixin.py:115} INFO - [2023-10-03 14:00:24,883] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:00:24,917] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.211 seconds
[2023-10-03 14:00:55,180] {processor.py:153} INFO - Started process (PID=2286) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:00:55,181] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:00:55,182] {logging_mixin.py:115} INFO - [2023-10-03 14:00:55,182] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:00:55,211] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:00:55,405] {logging_mixin.py:115} INFO - [2023-10-03 14:00:55,405] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:00:55,429] {logging_mixin.py:115} INFO - [2023-10-03 14:00:55,429] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:00:55,460] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.286 seconds
[2023-10-03 14:01:26,190] {processor.py:153} INFO - Started process (PID=2348) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:01:26,191] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:01:26,192] {logging_mixin.py:115} INFO - [2023-10-03 14:01:26,192] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:01:26,215] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:01:26,377] {logging_mixin.py:115} INFO - [2023-10-03 14:01:26,377] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:01:26,408] {logging_mixin.py:115} INFO - [2023-10-03 14:01:26,408] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:01:26,477] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.290 seconds
[2023-10-03 14:01:57,171] {processor.py:153} INFO - Started process (PID=2411) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:01:57,173] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:01:57,174] {logging_mixin.py:115} INFO - [2023-10-03 14:01:57,174] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:01:57,203] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:01:57,336] {logging_mixin.py:115} INFO - [2023-10-03 14:01:57,335] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:01:57,354] {logging_mixin.py:115} INFO - [2023-10-03 14:01:57,354] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:01:57,389] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.225 seconds
[2023-10-03 14:02:28,050] {processor.py:153} INFO - Started process (PID=2464) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:02:28,051] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:02:28,052] {logging_mixin.py:115} INFO - [2023-10-03 14:02:28,052] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:02:28,087] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:02:28,263] {logging_mixin.py:115} INFO - [2023-10-03 14:02:28,263] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:02:28,286] {logging_mixin.py:115} INFO - [2023-10-03 14:02:28,286] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:02:28,321] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.279 seconds
[2023-10-03 14:02:58,684] {processor.py:153} INFO - Started process (PID=2527) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:02:58,685] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:02:58,686] {logging_mixin.py:115} INFO - [2023-10-03 14:02:58,686] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:02:58,721] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:02:58,988] {logging_mixin.py:115} INFO - [2023-10-03 14:02:58,988] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:02:59,031] {logging_mixin.py:115} INFO - [2023-10-03 14:02:59,031] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:02:59,073] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.393 seconds
[2023-10-03 14:03:29,770] {processor.py:153} INFO - Started process (PID=2580) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:03:29,771] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:03:29,772] {logging_mixin.py:115} INFO - [2023-10-03 14:03:29,772] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:03:29,793] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:03:29,926] {logging_mixin.py:115} INFO - [2023-10-03 14:03:29,926] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:03:29,945] {logging_mixin.py:115} INFO - [2023-10-03 14:03:29,945] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:03:29,994] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.227 seconds
[2023-10-03 14:04:00,417] {processor.py:153} INFO - Started process (PID=2642) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:04:00,418] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:04:00,420] {logging_mixin.py:115} INFO - [2023-10-03 14:04:00,420] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:04:00,440] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:04:00,573] {logging_mixin.py:115} INFO - [2023-10-03 14:04:00,573] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:04:00,592] {logging_mixin.py:115} INFO - [2023-10-03 14:04:00,592] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:04:00,626] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.212 seconds
[2023-10-03 14:04:30,731] {processor.py:153} INFO - Started process (PID=2704) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:04:30,732] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:04:30,734] {logging_mixin.py:115} INFO - [2023-10-03 14:04:30,734] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:04:30,754] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:04:30,914] {logging_mixin.py:115} INFO - [2023-10-03 14:04:30,914] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:04:30,937] {logging_mixin.py:115} INFO - [2023-10-03 14:04:30,936] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:04:30,967] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.239 seconds
[2023-10-03 14:05:01,127] {processor.py:153} INFO - Started process (PID=2757) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:05:01,128] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:05:01,129] {logging_mixin.py:115} INFO - [2023-10-03 14:05:01,129] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:05:01,156] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:05:01,288] {logging_mixin.py:115} INFO - [2023-10-03 14:05:01,288] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:05:01,308] {logging_mixin.py:115} INFO - [2023-10-03 14:05:01,308] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:05:01,342] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.218 seconds
[2023-10-03 14:05:32,206] {processor.py:153} INFO - Started process (PID=2819) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:05:32,207] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:05:32,209] {logging_mixin.py:115} INFO - [2023-10-03 14:05:32,208] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:05:32,241] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:05:32,361] {logging_mixin.py:115} INFO - [2023-10-03 14:05:32,361] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:05:32,379] {logging_mixin.py:115} INFO - [2023-10-03 14:05:32,379] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:05:32,415] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.215 seconds
[2023-10-03 14:06:02,748] {processor.py:153} INFO - Started process (PID=2873) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:06:02,749] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:06:02,749] {logging_mixin.py:115} INFO - [2023-10-03 14:06:02,749] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:06:02,774] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:06:02,904] {logging_mixin.py:115} INFO - [2023-10-03 14:06:02,903] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:06:02,923] {logging_mixin.py:115} INFO - [2023-10-03 14:06:02,923] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:06:02,946] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.202 seconds
[2023-10-03 14:06:33,298] {processor.py:153} INFO - Started process (PID=2935) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:06:33,298] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:06:33,299] {logging_mixin.py:115} INFO - [2023-10-03 14:06:33,299] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:06:33,318] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:06:33,443] {logging_mixin.py:115} INFO - [2023-10-03 14:06:33,442] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:06:33,461] {logging_mixin.py:115} INFO - [2023-10-03 14:06:33,461] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:06:33,494] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.203 seconds
[2023-10-03 14:07:03,599] {processor.py:153} INFO - Started process (PID=2989) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:07:03,600] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:07:03,601] {logging_mixin.py:115} INFO - [2023-10-03 14:07:03,601] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:07:03,622] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:07:03,743] {logging_mixin.py:115} INFO - [2023-10-03 14:07:03,743] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:07:03,763] {logging_mixin.py:115} INFO - [2023-10-03 14:07:03,763] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:07:03,844] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.250 seconds
[2023-10-03 14:07:34,569] {processor.py:153} INFO - Started process (PID=3052) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:07:34,570] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:07:34,571] {logging_mixin.py:115} INFO - [2023-10-03 14:07:34,571] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:07:34,598] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:07:34,748] {logging_mixin.py:115} INFO - [2023-10-03 14:07:34,748] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:07:34,768] {logging_mixin.py:115} INFO - [2023-10-03 14:07:34,768] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:07:34,801] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.237 seconds
[2023-10-03 14:08:04,903] {processor.py:153} INFO - Started process (PID=3114) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:08:04,905] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:08:04,906] {logging_mixin.py:115} INFO - [2023-10-03 14:08:04,906] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:08:04,928] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:08:05,051] {logging_mixin.py:115} INFO - [2023-10-03 14:08:05,051] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:08:05,069] {logging_mixin.py:115} INFO - [2023-10-03 14:08:05,069] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:08:05,099] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.201 seconds
[2023-10-03 14:08:35,609] {processor.py:153} INFO - Started process (PID=3168) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:08:35,610] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:08:35,611] {logging_mixin.py:115} INFO - [2023-10-03 14:08:35,611] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:08:35,628] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:08:35,747] {logging_mixin.py:115} INFO - [2023-10-03 14:08:35,747] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:08:35,766] {logging_mixin.py:115} INFO - [2023-10-03 14:08:35,766] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:08:35,790] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.186 seconds
[2023-10-03 14:09:06,228] {processor.py:153} INFO - Started process (PID=3231) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:09:06,228] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:09:06,229] {logging_mixin.py:115} INFO - [2023-10-03 14:09:06,229] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:09:06,245] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:09:06,378] {logging_mixin.py:115} INFO - [2023-10-03 14:09:06,378] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:09:06,397] {logging_mixin.py:115} INFO - [2023-10-03 14:09:06,397] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:09:06,467] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.242 seconds
[2023-10-03 14:09:36,619] {processor.py:153} INFO - Started process (PID=3284) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:09:36,620] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:09:36,621] {logging_mixin.py:115} INFO - [2023-10-03 14:09:36,621] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:09:36,639] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:09:36,790] {logging_mixin.py:115} INFO - [2023-10-03 14:09:36,790] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:09:36,819] {logging_mixin.py:115} INFO - [2023-10-03 14:09:36,819] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:09:36,904] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.288 seconds
[2023-10-03 14:10:07,238] {processor.py:153} INFO - Started process (PID=3346) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:10:07,239] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:10:07,240] {logging_mixin.py:115} INFO - [2023-10-03 14:10:07,240] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:10:07,262] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:10:07,414] {logging_mixin.py:115} INFO - [2023-10-03 14:10:07,414] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:10:07,434] {logging_mixin.py:115} INFO - [2023-10-03 14:10:07,434] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:10:07,471] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.237 seconds
[2023-10-03 14:10:37,623] {processor.py:153} INFO - Started process (PID=3406) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:10:37,623] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:10:37,625] {logging_mixin.py:115} INFO - [2023-10-03 14:10:37,624] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:10:37,643] {processor.py:651} INFO - DAG(s) dict_keys(['dag_con_catchup']) retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:10:37,793] {logging_mixin.py:115} INFO - [2023-10-03 14:10:37,793] {dag.py:2420} INFO - Sync 1 DAGs
[2023-10-03 14:10:37,818] {logging_mixin.py:115} INFO - [2023-10-03 14:10:37,818] {dag.py:2972} INFO - Setting next_dagrun for dag_con_catchup to 2023-10-01T00:00:00+00:00, run_after=2023-10-02T00:00:00+00:00
[2023-10-03 14:10:37,893] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.273 seconds
[2023-10-03 14:11:01,590] {processor.py:153} INFO - Started process (PID=3455) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:11:01,591] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:11:01,592] {logging_mixin.py:115} INFO - [2023-10-03 14:11:01,592] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:11:03,296] {logging_mixin.py:115} INFO - [2023-10-03 14:11:03,291] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:11:03,297] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:11:03,372] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 1.785 seconds
[2023-10-03 14:11:33,536] {processor.py:153} INFO - Started process (PID=3511) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:11:33,536] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:11:33,537] {logging_mixin.py:115} INFO - [2023-10-03 14:11:33,537] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:11:33,903] {logging_mixin.py:115} INFO - [2023-10-03 14:11:33,898] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:11:33,905] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:11:33,953] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.421 seconds
[2023-10-03 14:12:04,012] {processor.py:153} INFO - Started process (PID=3575) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:12:04,013] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:12:04,014] {logging_mixin.py:115} INFO - [2023-10-03 14:12:04,013] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:12:04,395] {logging_mixin.py:115} INFO - [2023-10-03 14:12:04,391] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:12:04,396] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:12:04,427] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.419 seconds
[2023-10-03 14:12:34,649] {processor.py:153} INFO - Started process (PID=3629) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:12:34,650] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:12:34,651] {logging_mixin.py:115} INFO - [2023-10-03 14:12:34,651] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:12:35,078] {logging_mixin.py:115} INFO - [2023-10-03 14:12:35,075] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:12:35,079] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:12:35,118] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.471 seconds
[2023-10-03 14:13:05,226] {processor.py:153} INFO - Started process (PID=3692) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:13:05,230] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:13:05,231] {logging_mixin.py:115} INFO - [2023-10-03 14:13:05,231] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:13:05,631] {logging_mixin.py:115} INFO - [2023-10-03 14:13:05,627] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:13:05,631] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:13:05,666] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.445 seconds
[2023-10-03 14:13:35,702] {processor.py:153} INFO - Started process (PID=3755) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:13:35,703] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:13:35,703] {logging_mixin.py:115} INFO - [2023-10-03 14:13:35,703] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:13:36,258] {logging_mixin.py:115} INFO - [2023-10-03 14:13:36,254] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:13:36,259] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:13:36,298] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.600 seconds
[2023-10-03 14:14:06,495] {processor.py:153} INFO - Started process (PID=3810) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:14:06,495] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:14:06,496] {logging_mixin.py:115} INFO - [2023-10-03 14:14:06,496] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:14:06,904] {logging_mixin.py:115} INFO - [2023-10-03 14:14:06,901] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:14:06,905] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:14:06,946] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.455 seconds
[2023-10-03 14:14:36,980] {processor.py:153} INFO - Started process (PID=3874) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:14:36,981] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:14:36,982] {logging_mixin.py:115} INFO - [2023-10-03 14:14:36,981] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:14:37,367] {logging_mixin.py:115} INFO - [2023-10-03 14:14:37,362] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:14:37,369] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:14:37,405] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.429 seconds
[2023-10-03 14:15:07,586] {processor.py:153} INFO - Started process (PID=3928) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:15:07,587] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:15:07,588] {logging_mixin.py:115} INFO - [2023-10-03 14:15:07,587] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:15:07,950] {logging_mixin.py:115} INFO - [2023-10-03 14:15:07,945] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:15:07,951] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:15:07,993] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.410 seconds
[2023-10-03 14:15:38,232] {processor.py:153} INFO - Started process (PID=3991) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:15:38,233] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:15:38,233] {logging_mixin.py:115} INFO - [2023-10-03 14:15:38,233] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:15:38,595] {logging_mixin.py:115} INFO - [2023-10-03 14:15:38,590] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:15:38,596] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:15:38,633] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.404 seconds
[2023-10-03 14:16:08,934] {processor.py:153} INFO - Started process (PID=4052) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:16:08,935] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:16:08,936] {logging_mixin.py:115} INFO - [2023-10-03 14:16:08,936] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:16:09,363] {logging_mixin.py:115} INFO - [2023-10-03 14:16:09,355] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:16:09,365] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:16:09,463] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.534 seconds
[2023-10-03 14:16:40,032] {processor.py:153} INFO - Started process (PID=4108) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:16:40,033] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:16:40,034] {logging_mixin.py:115} INFO - [2023-10-03 14:16:40,034] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:16:40,367] {logging_mixin.py:115} INFO - [2023-10-03 14:16:40,360] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:16:40,368] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:16:40,483] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.456 seconds
[2023-10-03 14:17:10,771] {processor.py:153} INFO - Started process (PID=4171) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:17:10,772] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:17:10,773] {logging_mixin.py:115} INFO - [2023-10-03 14:17:10,772] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:17:11,074] {logging_mixin.py:115} INFO - [2023-10-03 14:17:11,069] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:17:11,075] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:17:11,113] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.346 seconds
[2023-10-03 14:17:41,341] {processor.py:153} INFO - Started process (PID=4225) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:17:41,345] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:17:41,348] {logging_mixin.py:115} INFO - [2023-10-03 14:17:41,348] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:17:41,614] {logging_mixin.py:115} INFO - [2023-10-03 14:17:41,609] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:17:41,615] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:17:41,647] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.327 seconds
[2023-10-03 14:18:12,211] {processor.py:153} INFO - Started process (PID=4288) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:18:12,212] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:18:12,214] {logging_mixin.py:115} INFO - [2023-10-03 14:18:12,214] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:18:12,471] {logging_mixin.py:115} INFO - [2023-10-03 14:18:12,466] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:18:12,472] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:18:12,510] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.307 seconds
[2023-10-03 14:18:42,682] {processor.py:153} INFO - Started process (PID=4342) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:18:42,683] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:18:42,684] {logging_mixin.py:115} INFO - [2023-10-03 14:18:42,684] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:18:42,981] {logging_mixin.py:115} INFO - [2023-10-03 14:18:42,977] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:18:42,982] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:18:43,025] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.348 seconds
[2023-10-03 14:19:13,256] {processor.py:153} INFO - Started process (PID=4405) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:19:13,257] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:19:13,258] {logging_mixin.py:115} INFO - [2023-10-03 14:19:13,258] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:19:13,518] {logging_mixin.py:115} INFO - [2023-10-03 14:19:13,514] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:19:13,519] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:19:13,567] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.317 seconds
[2023-10-03 14:19:43,760] {processor.py:153} INFO - Started process (PID=4468) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:19:43,761] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:19:43,762] {logging_mixin.py:115} INFO - [2023-10-03 14:19:43,762] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:19:44,021] {logging_mixin.py:115} INFO - [2023-10-03 14:19:44,016] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:19:44,022] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:19:44,056] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.300 seconds
[2023-10-03 14:20:14,364] {processor.py:153} INFO - Started process (PID=4522) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:20:14,366] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:20:14,367] {logging_mixin.py:115} INFO - [2023-10-03 14:20:14,367] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:20:14,638] {logging_mixin.py:115} INFO - [2023-10-03 14:20:14,633] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:20:14,640] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:20:14,680] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.322 seconds
[2023-10-03 14:20:45,268] {processor.py:153} INFO - Started process (PID=4585) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:20:45,269] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:20:45,270] {logging_mixin.py:115} INFO - [2023-10-03 14:20:45,270] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:20:45,536] {logging_mixin.py:115} INFO - [2023-10-03 14:20:45,531] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:20:45,537] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:20:45,595] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.334 seconds
[2023-10-03 14:21:15,689] {processor.py:153} INFO - Started process (PID=4649) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:21:15,690] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:21:15,691] {logging_mixin.py:115} INFO - [2023-10-03 14:21:15,691] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:21:15,972] {logging_mixin.py:115} INFO - [2023-10-03 14:21:15,967] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:21:15,973] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:21:16,044] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.359 seconds
[2023-10-03 14:21:46,813] {processor.py:153} INFO - Started process (PID=4704) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:21:46,814] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:21:46,814] {logging_mixin.py:115} INFO - [2023-10-03 14:21:46,814] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:21:47,065] {logging_mixin.py:115} INFO - [2023-10-03 14:21:47,061] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:21:47,067] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:21:47,128] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.319 seconds
[2023-10-03 14:22:17,311] {processor.py:153} INFO - Started process (PID=4768) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:22:17,312] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:22:17,314] {logging_mixin.py:115} INFO - [2023-10-03 14:22:17,314] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:22:17,612] {logging_mixin.py:115} INFO - [2023-10-03 14:22:17,607] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:22:17,613] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:22:17,703] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.399 seconds
[2023-10-03 14:22:47,926] {processor.py:153} INFO - Started process (PID=4822) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:22:47,926] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:22:47,927] {logging_mixin.py:115} INFO - [2023-10-03 14:22:47,927] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:22:48,175] {logging_mixin.py:115} INFO - [2023-10-03 14:22:48,169] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:22:48,176] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:22:48,218] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.296 seconds
[2023-10-03 14:23:18,397] {processor.py:153} INFO - Started process (PID=4885) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:23:18,397] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:23:18,398] {logging_mixin.py:115} INFO - [2023-10-03 14:23:18,398] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:23:18,657] {logging_mixin.py:115} INFO - [2023-10-03 14:23:18,653] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:23:18,658] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:23:18,696] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.302 seconds
[2023-10-03 14:23:49,517] {processor.py:153} INFO - Started process (PID=4939) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:23:49,518] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:23:49,519] {logging_mixin.py:115} INFO - [2023-10-03 14:23:49,519] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:23:49,776] {logging_mixin.py:115} INFO - [2023-10-03 14:23:49,770] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:23:49,777] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:23:49,816] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.302 seconds
[2023-10-03 14:24:19,942] {processor.py:153} INFO - Started process (PID=5002) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:24:19,943] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:24:19,944] {logging_mixin.py:115} INFO - [2023-10-03 14:24:19,944] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:24:20,223] {logging_mixin.py:115} INFO - [2023-10-03 14:24:20,219] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:24:20,224] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:24:20,264] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.326 seconds
[2023-10-03 14:24:51,188] {processor.py:153} INFO - Started process (PID=5066) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:24:51,189] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:24:51,191] {logging_mixin.py:115} INFO - [2023-10-03 14:24:51,191] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:24:51,432] {logging_mixin.py:115} INFO - [2023-10-03 14:24:51,426] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:24:51,433] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:24:51,475] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.293 seconds
[2023-10-03 14:25:21,602] {processor.py:153} INFO - Started process (PID=5119) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:25:21,603] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:25:21,606] {logging_mixin.py:115} INFO - [2023-10-03 14:25:21,605] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:25:21,857] {logging_mixin.py:115} INFO - [2023-10-03 14:25:21,852] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:25:21,858] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:25:21,903] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.313 seconds
[2023-10-03 14:25:52,463] {processor.py:153} INFO - Started process (PID=5182) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:25:52,463] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:25:52,464] {logging_mixin.py:115} INFO - [2023-10-03 14:25:52,464] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:25:52,736] {logging_mixin.py:115} INFO - [2023-10-03 14:25:52,732] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:25:52,738] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:25:52,790] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.331 seconds
[2023-10-03 14:26:23,137] {processor.py:153} INFO - Started process (PID=5245) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:26:23,137] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:26:23,138] {logging_mixin.py:115} INFO - [2023-10-03 14:26:23,138] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:26:23,417] {logging_mixin.py:115} INFO - [2023-10-03 14:26:23,412] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:26:23,418] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:26:23,505] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.371 seconds
[2023-10-03 14:26:53,763] {processor.py:153} INFO - Started process (PID=5299) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:26:53,764] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:26:53,766] {logging_mixin.py:115} INFO - [2023-10-03 14:26:53,766] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:26:54,071] {logging_mixin.py:115} INFO - [2023-10-03 14:26:54,066] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:26:54,073] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:26:54,111] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.358 seconds
[2023-10-03 14:27:24,499] {processor.py:153} INFO - Started process (PID=5362) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:27:24,501] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:27:24,502] {logging_mixin.py:115} INFO - [2023-10-03 14:27:24,502] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:27:24,740] {logging_mixin.py:115} INFO - [2023-10-03 14:27:24,734] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:27:24,741] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:27:24,880] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.388 seconds
[2023-10-03 14:27:55,239] {processor.py:153} INFO - Started process (PID=5423) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:27:55,240] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:27:55,240] {logging_mixin.py:115} INFO - [2023-10-03 14:27:55,240] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:27:55,492] {logging_mixin.py:115} INFO - [2023-10-03 14:27:55,488] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:27:55,494] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:27:55,525] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.290 seconds
[2023-10-03 14:28:26,035] {processor.py:153} INFO - Started process (PID=5479) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:28:26,036] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:28:26,037] {logging_mixin.py:115} INFO - [2023-10-03 14:28:26,037] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:28:26,362] {logging_mixin.py:115} INFO - [2023-10-03 14:28:26,357] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:28:26,364] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:28:26,413] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.381 seconds
[2023-10-03 14:28:56,597] {processor.py:153} INFO - Started process (PID=5542) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:28:56,598] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:28:56,600] {logging_mixin.py:115} INFO - [2023-10-03 14:28:56,600] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:28:56,855] {logging_mixin.py:115} INFO - [2023-10-03 14:28:56,850] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:28:56,856] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:28:56,895] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.308 seconds
[2023-10-03 14:29:27,141] {processor.py:153} INFO - Started process (PID=5596) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:29:27,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:29:27,144] {logging_mixin.py:115} INFO - [2023-10-03 14:29:27,143] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:29:27,386] {logging_mixin.py:115} INFO - [2023-10-03 14:29:27,381] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:29:27,387] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:29:27,428] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.293 seconds
[2023-10-03 14:29:57,768] {processor.py:153} INFO - Started process (PID=5659) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:29:57,770] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:29:57,772] {logging_mixin.py:115} INFO - [2023-10-03 14:29:57,772] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:29:58,065] {logging_mixin.py:115} INFO - [2023-10-03 14:29:58,059] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:29:58,066] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:29:58,110] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.352 seconds
[2023-10-03 14:30:28,346] {processor.py:153} INFO - Started process (PID=5722) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:30:28,348] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:30:28,350] {logging_mixin.py:115} INFO - [2023-10-03 14:30:28,350] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:30:28,589] {logging_mixin.py:115} INFO - [2023-10-03 14:30:28,584] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:30:28,590] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:30:28,627] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.288 seconds
[2023-10-03 14:30:58,815] {processor.py:153} INFO - Started process (PID=5776) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:30:58,815] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:30:58,816] {logging_mixin.py:115} INFO - [2023-10-03 14:30:58,816] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:30:59,066] {logging_mixin.py:115} INFO - [2023-10-03 14:30:59,061] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:30:59,067] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:30:59,108] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.297 seconds
[2023-10-03 14:31:29,494] {processor.py:153} INFO - Started process (PID=5839) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:31:29,495] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:31:29,496] {logging_mixin.py:115} INFO - [2023-10-03 14:31:29,496] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:31:29,743] {logging_mixin.py:115} INFO - [2023-10-03 14:31:29,738] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:31:29,744] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:31:29,782] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.293 seconds
[2023-10-03 14:31:59,908] {processor.py:153} INFO - Started process (PID=5902) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:31:59,909] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:31:59,910] {logging_mixin.py:115} INFO - [2023-10-03 14:31:59,910] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:32:00,190] {logging_mixin.py:115} INFO - [2023-10-03 14:32:00,186] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:32:00,192] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:32:00,231] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.326 seconds
[2023-10-03 14:32:30,395] {processor.py:153} INFO - Started process (PID=5956) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:32:30,396] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:32:30,397] {logging_mixin.py:115} INFO - [2023-10-03 14:32:30,397] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:32:30,730] {logging_mixin.py:115} INFO - [2023-10-03 14:32:30,726] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:32:30,731] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:32:30,771] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.379 seconds
[2023-10-03 14:33:00,966] {processor.py:153} INFO - Started process (PID=6019) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:33:00,967] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:33:00,968] {logging_mixin.py:115} INFO - [2023-10-03 14:33:00,968] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:33:01,235] {logging_mixin.py:115} INFO - [2023-10-03 14:33:01,230] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:33:01,237] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:33:01,270] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.312 seconds
[2023-10-03 14:33:31,423] {processor.py:153} INFO - Started process (PID=6073) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:33:31,424] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:33:31,424] {logging_mixin.py:115} INFO - [2023-10-03 14:33:31,424] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:33:31,692] {logging_mixin.py:115} INFO - [2023-10-03 14:33:31,688] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:33:31,694] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:33:31,735] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.316 seconds
[2023-10-03 14:34:02,041] {processor.py:153} INFO - Started process (PID=6136) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:34:02,042] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:34:02,044] {logging_mixin.py:115} INFO - [2023-10-03 14:34:02,044] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:34:02,302] {logging_mixin.py:115} INFO - [2023-10-03 14:34:02,296] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:34:02,303] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:34:02,385] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.354 seconds
[2023-10-03 14:34:32,548] {processor.py:153} INFO - Started process (PID=6199) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:34:32,549] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:34:32,549] {logging_mixin.py:115} INFO - [2023-10-03 14:34:32,549] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:34:32,814] {logging_mixin.py:115} INFO - [2023-10-03 14:34:32,808] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:34:32,816] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:34:32,867] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.323 seconds
[2023-10-03 14:35:02,954] {processor.py:153} INFO - Started process (PID=6253) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:35:02,955] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:35:02,957] {logging_mixin.py:115} INFO - [2023-10-03 14:35:02,956] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:35:03,202] {logging_mixin.py:115} INFO - [2023-10-03 14:35:03,197] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:35:03,203] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:35:03,240] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.292 seconds
[2023-10-03 14:35:33,713] {processor.py:153} INFO - Started process (PID=6316) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:35:33,713] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:35:33,714] {logging_mixin.py:115} INFO - [2023-10-03 14:35:33,714] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:35:33,959] {logging_mixin.py:115} INFO - [2023-10-03 14:35:33,954] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:35:33,960] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:35:33,997] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.287 seconds
[2023-10-03 14:36:04,246] {processor.py:153} INFO - Started process (PID=6370) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:36:04,248] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:36:04,249] {logging_mixin.py:115} INFO - [2023-10-03 14:36:04,249] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:36:04,574] {logging_mixin.py:115} INFO - [2023-10-03 14:36:04,569] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:36:04,575] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:36:04,659] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.420 seconds
[2023-10-03 14:36:34,858] {processor.py:153} INFO - Started process (PID=6433) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:36:34,860] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:36:34,861] {logging_mixin.py:115} INFO - [2023-10-03 14:36:34,861] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:36:35,112] {logging_mixin.py:115} INFO - [2023-10-03 14:36:35,107] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:36:35,113] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:36:35,152] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.300 seconds
[2023-10-03 14:37:05,221] {processor.py:153} INFO - Started process (PID=6496) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:37:05,223] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:37:05,223] {logging_mixin.py:115} INFO - [2023-10-03 14:37:05,223] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:37:05,475] {logging_mixin.py:115} INFO - [2023-10-03 14:37:05,472] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:37:05,476] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:37:05,525] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.308 seconds
[2023-10-03 14:37:35,876] {processor.py:153} INFO - Started process (PID=6550) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:37:35,880] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:37:35,881] {logging_mixin.py:115} INFO - [2023-10-03 14:37:35,881] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:37:36,148] {logging_mixin.py:115} INFO - [2023-10-03 14:37:36,143] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:37:36,149] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:37:36,198] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.331 seconds
[2023-10-03 14:38:06,266] {processor.py:153} INFO - Started process (PID=6613) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:38:06,267] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:38:06,267] {logging_mixin.py:115} INFO - [2023-10-03 14:38:06,267] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:38:06,507] {logging_mixin.py:115} INFO - [2023-10-03 14:38:06,502] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:38:06,508] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:38:06,591] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.328 seconds
[2023-10-03 14:38:36,962] {processor.py:153} INFO - Started process (PID=6667) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:38:36,963] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:38:36,964] {logging_mixin.py:115} INFO - [2023-10-03 14:38:36,964] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:38:37,235] {logging_mixin.py:115} INFO - [2023-10-03 14:38:37,231] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:38:37,237] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:38:37,288] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.335 seconds
[2023-10-03 14:39:07,633] {processor.py:153} INFO - Started process (PID=6730) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:39:07,634] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:39:07,636] {logging_mixin.py:115} INFO - [2023-10-03 14:39:07,636] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:39:07,873] {logging_mixin.py:115} INFO - [2023-10-03 14:39:07,868] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:39:07,874] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:39:07,911] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.286 seconds
[2023-10-03 14:39:37,997] {processor.py:153} INFO - Started process (PID=6793) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:39:37,998] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:39:37,999] {logging_mixin.py:115} INFO - [2023-10-03 14:39:37,999] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:39:38,303] {logging_mixin.py:115} INFO - [2023-10-03 14:39:38,300] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:39:38,304] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:39:38,402] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.409 seconds
[2023-10-03 14:40:09,077] {processor.py:153} INFO - Started process (PID=6848) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:40:09,085] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:40:09,087] {logging_mixin.py:115} INFO - [2023-10-03 14:40:09,086] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:40:09,395] {logging_mixin.py:115} INFO - [2023-10-03 14:40:09,391] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:40:09,396] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:40:09,450] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.387 seconds
[2023-10-03 14:40:39,971] {processor.py:153} INFO - Started process (PID=6911) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:40:39,973] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:40:39,974] {logging_mixin.py:115} INFO - [2023-10-03 14:40:39,974] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:40:40,230] {logging_mixin.py:115} INFO - [2023-10-03 14:40:40,224] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:40:40,231] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:40:40,536] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.571 seconds
[2023-10-03 14:41:10,954] {processor.py:153} INFO - Started process (PID=6965) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:41:10,956] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:41:10,957] {logging_mixin.py:115} INFO - [2023-10-03 14:41:10,957] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:41:11,270] {logging_mixin.py:115} INFO - [2023-10-03 14:41:11,265] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:41:11,271] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:41:11,315] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.375 seconds
[2023-10-03 14:41:41,624] {processor.py:153} INFO - Started process (PID=7028) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:41:41,626] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:41:41,627] {logging_mixin.py:115} INFO - [2023-10-03 14:41:41,627] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:41:41,883] {logging_mixin.py:115} INFO - [2023-10-03 14:41:41,878] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:41:41,884] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:41:41,946] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.332 seconds
[2023-10-03 14:42:12,170] {processor.py:153} INFO - Started process (PID=7091) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:42:12,171] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:42:12,172] {logging_mixin.py:115} INFO - [2023-10-03 14:42:12,172] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:42:12,453] {logging_mixin.py:115} INFO - [2023-10-03 14:42:12,449] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:42:12,454] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:42:12,488] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.322 seconds
[2023-10-03 14:42:42,750] {processor.py:153} INFO - Started process (PID=7145) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:42:42,751] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:42:42,751] {logging_mixin.py:115} INFO - [2023-10-03 14:42:42,751] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:42:42,986] {logging_mixin.py:115} INFO - [2023-10-03 14:42:42,981] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:42:42,988] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:42:43,021] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.274 seconds
[2023-10-03 14:43:13,415] {processor.py:153} INFO - Started process (PID=7209) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:43:13,416] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:43:13,417] {logging_mixin.py:115} INFO - [2023-10-03 14:43:13,417] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:43:13,650] {logging_mixin.py:115} INFO - [2023-10-03 14:43:13,644] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:43:13,651] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:43:13,686] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.274 seconds
[2023-10-03 14:43:43,937] {processor.py:153} INFO - Started process (PID=7263) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:43:43,939] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:43:43,940] {logging_mixin.py:115} INFO - [2023-10-03 14:43:43,940] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:43:44,186] {logging_mixin.py:115} INFO - [2023-10-03 14:43:44,181] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:43:44,187] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:43:44,224] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.294 seconds
[2023-10-03 14:44:14,539] {processor.py:153} INFO - Started process (PID=7327) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:44:14,540] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:44:14,541] {logging_mixin.py:115} INFO - [2023-10-03 14:44:14,541] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:44:14,784] {logging_mixin.py:115} INFO - [2023-10-03 14:44:14,779] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:44:14,786] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:44:14,823] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.290 seconds
[2023-10-03 14:44:44,999] {processor.py:153} INFO - Started process (PID=7390) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:44:44,999] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:44:45,000] {logging_mixin.py:115} INFO - [2023-10-03 14:44:45,000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:44:45,260] {logging_mixin.py:115} INFO - [2023-10-03 14:44:45,256] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:44:45,262] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:44:45,295] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.300 seconds
[2023-10-03 14:45:15,625] {processor.py:153} INFO - Started process (PID=7444) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:45:15,627] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:45:15,628] {logging_mixin.py:115} INFO - [2023-10-03 14:45:15,628] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:45:15,869] {logging_mixin.py:115} INFO - [2023-10-03 14:45:15,863] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:45:15,870] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:45:15,912] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.292 seconds
[2023-10-03 14:45:46,241] {processor.py:153} INFO - Started process (PID=7507) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:45:46,244] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:45:46,246] {logging_mixin.py:115} INFO - [2023-10-03 14:45:46,246] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:45:46,547] {logging_mixin.py:115} INFO - [2023-10-03 14:45:46,542] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:45:46,549] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:45:46,588] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.357 seconds
[2023-10-03 14:46:17,088] {processor.py:153} INFO - Started process (PID=7570) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:46:17,089] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:46:17,090] {logging_mixin.py:115} INFO - [2023-10-03 14:46:17,090] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:46:17,376] {logging_mixin.py:115} INFO - [2023-10-03 14:46:17,372] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:46:17,377] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:46:17,417] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.333 seconds
[2023-10-03 14:51:30,707] {processor.py:153} INFO - Started process (PID=44) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:51:30,709] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:51:30,734] {logging_mixin.py:115} INFO - [2023-10-03 14:51:30,734] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:51:31,516] {logging_mixin.py:115} INFO - [2023-10-03 14:51:31,511] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:51:31,519] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:51:31,645] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.945 seconds
[2023-10-03 14:52:01,807] {processor.py:153} INFO - Started process (PID=101) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:52:01,808] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:52:01,809] {logging_mixin.py:115} INFO - [2023-10-03 14:52:01,809] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:52:02,271] {logging_mixin.py:115} INFO - [2023-10-03 14:52:02,263] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:52:02,273] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:52:02,310] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.505 seconds
[2023-10-03 14:52:32,437] {processor.py:153} INFO - Started process (PID=165) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:52:32,438] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:52:32,439] {logging_mixin.py:115} INFO - [2023-10-03 14:52:32,439] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:52:32,870] {logging_mixin.py:115} INFO - [2023-10-03 14:52:32,866] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:52:32,871] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:52:32,914] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.480 seconds
[2023-10-03 14:53:03,549] {processor.py:153} INFO - Started process (PID=219) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:53:03,550] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:53:03,551] {logging_mixin.py:115} INFO - [2023-10-03 14:53:03,551] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:53:04,015] {logging_mixin.py:115} INFO - [2023-10-03 14:53:04,010] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:53:04,016] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:53:04,074] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.530 seconds
[2023-10-03 14:53:34,141] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:53:34,143] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:53:34,144] {logging_mixin.py:115} INFO - [2023-10-03 14:53:34,144] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:53:35,081] {logging_mixin.py:115} INFO - [2023-10-03 14:53:35,078] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:53:35,083] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:53:35,120] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.984 seconds
[2023-10-03 14:54:05,580] {processor.py:153} INFO - Started process (PID=337) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:54:05,588] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:54:05,589] {logging_mixin.py:115} INFO - [2023-10-03 14:54:05,589] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:54:05,969] {logging_mixin.py:115} INFO - [2023-10-03 14:54:05,966] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:54:05,970] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:54:06,018] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.443 seconds
[2023-10-03 14:54:36,512] {processor.py:153} INFO - Started process (PID=400) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:54:36,513] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:54:36,514] {logging_mixin.py:115} INFO - [2023-10-03 14:54:36,514] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:54:36,970] {logging_mixin.py:115} INFO - [2023-10-03 14:54:36,965] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:54:36,972] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:54:37,017] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.510 seconds
[2023-10-03 14:55:07,058] {processor.py:153} INFO - Started process (PID=455) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:55:07,059] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:55:07,060] {logging_mixin.py:115} INFO - [2023-10-03 14:55:07,060] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:55:07,652] {logging_mixin.py:115} INFO - [2023-10-03 14:55:07,648] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:55:07,653] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:55:07,743] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.690 seconds
[2023-10-03 14:55:37,838] {processor.py:153} INFO - Started process (PID=519) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:55:37,839] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:55:37,840] {logging_mixin.py:115} INFO - [2023-10-03 14:55:37,839] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:55:38,215] {logging_mixin.py:115} INFO - [2023-10-03 14:55:38,211] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:55:38,217] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:55:38,256] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.422 seconds
[2023-10-03 14:56:08,892] {processor.py:153} INFO - Started process (PID=582) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:56:08,893] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:56:08,893] {logging_mixin.py:115} INFO - [2023-10-03 14:56:08,893] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:56:09,317] {logging_mixin.py:115} INFO - [2023-10-03 14:56:09,311] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:56:09,318] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:56:09,358] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.468 seconds
[2023-10-03 14:56:39,495] {processor.py:153} INFO - Started process (PID=637) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:56:39,496] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:56:39,498] {logging_mixin.py:115} INFO - [2023-10-03 14:56:39,497] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:56:40,018] {logging_mixin.py:115} INFO - [2023-10-03 14:56:40,015] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:56:40,019] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:56:40,090] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.600 seconds
[2023-10-03 14:57:10,170] {processor.py:153} INFO - Started process (PID=701) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:57:10,171] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:57:10,172] {logging_mixin.py:115} INFO - [2023-10-03 14:57:10,172] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:57:10,547] {logging_mixin.py:115} INFO - [2023-10-03 14:57:10,543] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:57:10,548] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:57:10,579] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.413 seconds
[2023-10-03 14:57:40,667] {processor.py:153} INFO - Started process (PID=756) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:57:40,668] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:57:40,669] {logging_mixin.py:115} INFO - [2023-10-03 14:57:40,669] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:57:41,016] {logging_mixin.py:115} INFO - [2023-10-03 14:57:41,012] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:57:41,017] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:57:41,052] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.388 seconds
[2023-10-03 14:58:11,140] {processor.py:153} INFO - Started process (PID=819) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:58:11,141] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:58:11,142] {logging_mixin.py:115} INFO - [2023-10-03 14:58:11,142] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:58:11,540] {logging_mixin.py:115} INFO - [2023-10-03 14:58:11,535] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:58:11,541] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:58:11,585] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.449 seconds
[2023-10-03 14:58:42,188] {processor.py:153} INFO - Started process (PID=882) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:58:42,189] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:58:42,190] {logging_mixin.py:115} INFO - [2023-10-03 14:58:42,189] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:58:42,706] {logging_mixin.py:115} INFO - [2023-10-03 14:58:42,702] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:58:42,707] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:58:42,815] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.632 seconds
[2023-10-03 14:59:12,952] {processor.py:153} INFO - Started process (PID=936) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:59:12,952] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:59:12,953] {logging_mixin.py:115} INFO - [2023-10-03 14:59:12,953] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:59:13,310] {logging_mixin.py:115} INFO - [2023-10-03 14:59:13,306] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:59:13,310] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:59:13,348] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.400 seconds
[2023-10-03 14:59:43,392] {processor.py:153} INFO - Started process (PID=1000) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:59:43,393] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 14:59:43,394] {logging_mixin.py:115} INFO - [2023-10-03 14:59:43,394] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:59:43,791] {logging_mixin.py:115} INFO - [2023-10-03 14:59:43,787] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 14:59:43,793] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 14:59:43,848] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.459 seconds
[2023-10-03 15:00:13,899] {processor.py:153} INFO - Started process (PID=1054) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:00:13,899] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 15:00:13,900] {logging_mixin.py:115} INFO - [2023-10-03 15:00:13,900] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:00:14,264] {logging_mixin.py:115} INFO - [2023-10-03 15:00:14,260] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 15:00:14,265] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:00:14,396] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.501 seconds
[2023-10-03 15:00:44,849] {processor.py:153} INFO - Started process (PID=1120) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:00:44,850] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 15:00:44,850] {logging_mixin.py:115} INFO - [2023-10-03 15:00:44,850] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:00:45,312] {logging_mixin.py:115} INFO - [2023-10-03 15:00:45,307] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 15:00:45,313] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:00:45,461] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.615 seconds
[2023-10-03 15:01:15,833] {processor.py:153} INFO - Started process (PID=1182) to work on /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:01:15,834] {processor.py:641} INFO - Processing file /opt/airflow/dags/Dag_Entrega3.py for tasks to queue
[2023-10-03 15:01:15,836] {logging_mixin.py:115} INFO - [2023-10-03 15:01:15,836] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:01:16,373] {logging_mixin.py:115} INFO - [2023-10-03 15:01:16,368] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/Dag_Entrega3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_Entrega3.py", line 4, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-10-03 15:01:16,375] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_Entrega3.py
[2023-10-03 15:01:16,428] {processor.py:161} INFO - Processing /opt/airflow/dags/Dag_Entrega3.py took 0.598 seconds
